#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

post_description='[See an example result here](https://github.com/WillAbides/benchdiff-action/runs/1691721812).

To learn about the benchdiff command that this action runs, visit https://github.com/WillAbides/benchdiff.'

script/action-doc action.yml \
 --post-description-text "$post_description" \
 >./README.md
