name: ci
on: [ push, workflow_dispatch ]
jobs:
  cibuild:
    name: cibuild
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: script/generate --check
      - run: script/lint
  text-bench:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: golang/text
          ref: v0.3.6
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: "~1.15"
      - uses: .
        id: benchdiff
        with:
          benchdiff_version: 0.9.1
          status_sha: ${{ github.sha }}
          status_name: text-bench-result
          status_on_degraded: neutral
          benchdiff_args: |
            --packages ./unicode/...
            --cpu=1
            --count=10
            --warmup-count=1
            --benchtime=10ms
            --tolerance=50
            --base-ref v0.3.5
            --debug
      - name: Summary
        run: |
          echo "${{ steps.benchdiff.outputs.benchstat_output }}" > benchdiff-report.md
          {
            echo "## Benchdiff Results"
            echo ""
            echo 'Head: `${{ steps.benchdiff.outputs.head_sha }}`'
            echo 'Base: `${{ steps.benchdiff.outputs.base_sha }}`'
            echo 'Degraded: `${{ steps.benchdiff.outputs.degraded_result }}`'
            echo ""
            echo "<details>"
            echo "<summary>See results</summary>"
            echo ""
            echo "${{ steps.benchdiff.outputs.benchstat_output }}"
            echo ""
            echo "</details>"
          } >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v3
        with:
          name: benchdiff-report
          path: benchdiff-report.md
